repositories:
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets
  - name: influxdata
    url: https://helm.influxdata.com/

releases:
  - name: sealed-secrets
    namespace: kube-system
    chart: sealed-secrets/sealed-secrets
    values:
      - fullnameOverride: sealed-secrets-controller
  - name: influxdb2
    namespace: influxdb
    createNamespace: true
    chart: influxdata/influxdb2
    values:
      - persistence:
          enabled: true
          size: 20Gi
          subPath: "influxdb2"
